config/routes.rb
Rails.application.routes.draw do
  root 'programs#index'
  
  resources :programs
  resources :discs
  resources :persons
  resources :locations
  resources :series
  resources :packages
  resources :alternate_titles
  resources :program_version_clusters

  #cloning
  get '/program/:id/new_version', to: 'programs#new_version', as: :program_new_version

  #reports
  get 'reports/program/duplicates', to: 'programs#duplicates_report'
  get 'reports/program/unused', to: 'programs#unused_report'
  get 'reports/disc/no_location', to: 'discs#no_location_report'
  get 'reports/package/no_discs', to: 'packages#no_discs_report'

  #modal selectors
  get "select/program/:link_id/:set_id", to: 'programs#selector', as: :program_selector
  get "select/search/program/:term", to: 'programs#selector_search', as: :program_selector_search
  get "select/person/:link_id/:set_id", to: 'persons#selector', as: :person_selector
  get "select/search/person/:term", to: 'persons#selector_search', as: :person_selector_search
  get "select/series/:link_id/:set_id", to: 'series#selector', as: :series_selector
  get "select/search/series/:term", to: 'series#selector_search', as: :series_selector_search
  get "select/package/:link_id/:set_id", to: 'packages#selector', as: :package_selector
  get "select/search/package/:term", to: 'packages#selector_search', as: :package_selector_search
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
    validates :name, presence: true

    belongs_to :program_version_cluster, optional: true
    has_many :program_persons, dependent: :delete_all
    has_many :persons, through: :program_persons, source: :person
    has_many :disc_programs, dependent: :delete_all
    has_many :discs, through: :disc_programs
    has_many :series_programs, dependent: :delete_all
    has_many :series, through: :series_programs
    has_many :alternate_titles, dependent: :delete_all
    accepts_nested_attributes_for :series_programs, reject_if: proc { |attributes| attributes['series_id'].blank? }
    accepts_nested_attributes_for :program_persons, reject_if: proc { |attributes| attributes['person_id'].blank? }
    accepts_nested_attributes_for :alternate_titles, reject_if: proc { |attributes| attributes['name'].blank? }

    def self.duplicates
      joins(:disc_programs).group('program_id').having('count(program_id) > 1')
    end

    def self.unused
      left_outer_joins(:disc_programs).where(disc_programs: {id: nil})
    end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def index
    if params[:search]
      @search = params[:search]
      @search_results_programs = ProgramsSearch.search_by_name(params[:search]).paginate(page: @page, per_page: 15)
      respond_to do |format|
        format.html { @programs = @search_results_programs}
        format.js { render partial: 'search-results'}
      end
    else
      @programs = ProgramsSearch.all_by_name.paginate(page: @page, per_page: 15)
    end
  end

  def show
    @program = Program.find params[:id]
    @search = params[:search]
  end

  def new
    @program = Program.new
    @series = Series.all_sort_by_name
  end

  def edit
    @program = Program.find params[:id]
    @series = Series.all_sort_by_name
    @search = params[:search]
  end

  def create
    @program = Program.new program_params
    if @program.save
      redirect_to @program
    else
      @series = Series.all_sort_by_name
      render 'new'
    end
  end

  def update
    @program = Program.find(params[:id])
    @search = params[:search]
    if @program.update program_params
      redirect_to program_path(@program, page: @page, search: @search)
    else
      @series = Series.all_sort_by_name
      render 'edit'
    end
  end

  def destroy
    program = Program.find params[:id]
    program.destroy
    redirect_to action: 'index'
  end

  def duplicates_report
    @programs = Program.duplicates.paginate(page: params[:page], per_page: 15)
  end

  def unused_report
    @programs = Program.unused.paginate(page: params[:page], per_page: 15)
  end

  def selector
    @set_id = params[:set_id]
    @link_id = params[:link_id]
    @programs = ProgramsSearch.all_by_name
    respond_to do |format|
      format.html
      format.js
    end
  end

  def selector_search
    search_term = params[:term]
    @programs = ProgramsSearch.search_by_name search_term
    respond_to do |format|
      format.js
    end
  end

  def new_version
    op = Program.find params[:id]
    np = op.dup
    np.save!
    op.persons.each {|d| np.persons << d}
    op.series.each {|s| np.series << s}
    op.alternate_titles.each {|at| np.alternate_titles << AlternateTitle.new(name: at.name)}
    if op.program_version_cluster.nil?
      pvc = ProgramVersionCluster.create!
      pvc.programs << op
      pvc.programs << np
    end
    redirect_to action: 'edit', id: np.id
  end

  private

  def program_params
    program_persons_attributes = params[:program][:program_persons_attributes]
    unless program_persons_attributes.nil?
      d_ids = program_persons_attributes.to_unsafe_h.select {
        |pda| 
        destroy_val = program_persons_attributes[pda][:_destroy]
        destroy_val != '1'
      }.collect {
        |pda| 
        pda[1][:person_id]
      }.uniq
      params[:program][:person_ids] = d_ids
    end

    series_programs_attributes = params[:program][:series_programs_attributes]
    unless series_programs_attributes.nil?
      sids = series_programs_attributes.to_unsafe_h.collect {|pda| pda[1][:series_id]}.uniq
      params[:program][:series_ids] = sids
    end

    params[:program][:program_persons_attributes] = nil
    params[:program][:series_programs_attributes] = nil

    params.require(:program).permit(:name, :sort_name, :year, :version, :minutes, person_ids:[], series_ids:[], alternate_titles_attributes:[:program_id, :name])
  end

end

app/helpers/programs_helper.rb
module ProgramsHelper

  def program_capsule(program)
    year = program.year.blank? ? '' : " (#{program.year})"
    s_names = program.series.pluck(:name)
    series = s_names.any? ? " - #{s_names.join(', ')}" : ''
    version = program.version.blank? ? '' : " (#{program.version})"
    "#{program.name}#{year}#{series}#{version}"
  end

  def program_capsule_short(program)
    version = program.version.blank? ? '' : " - #{program.version}"
    "#{program_capsule_year(program)}#{version}"
  end

  def program_capsule_year(program)
    year = program.year.blank? ? '' : " (#{program.year})"
    "#{program.name}#{year}"
  end

  def display_length(minutes)
    return '' if minutes.nil?
    hours = minutes / 60
    minutes = minutes % 60
    min_display = minutes > 0 ? " #{minutes} min" : ''
    "#{hours} #{'hr'.pluralize(hours)}#{min_display}"
  end

  def duplicate_report_display(program)
    discs = program.discs.map { |d|
      package = d.package.nil? ? '' : "#{link_to d.package.name, package_path(d.package)} "
      disc = "#{d.format} (#{d.location.name})"
      "#{package}#{link_to disc, disc_path(d)}"
    }.join(', ')
    raw "#{link_to program.name, program_path(program)} - #{discs}"
  end

end

app/views/programs/_alternate_title_fields.html.haml
.alternate-title-fields
  .form-group
    = f.text_field :name
    = f.label :name

app/views/programs/_cluster_versions.html.haml
- if @program.program_version_cluster.present?
  .cluster
    - if mode == 'view'
      = link_to 'part of cluster', program_version_cluster_path(@program.program_version_cluster.id)
    - else
      = 'part of cluster'
    with
    - @program.program_version_cluster.programs.each do |p|
      - unless p.id == @program.id
        - if mode == 'view'
          = link_to p.version, program_path(p.id)
        - else
          = p.version
        - unless p == @program.program_version_cluster.programs.last
          = '/'

app/views/programs/_paginated_programs.html.haml
.top_pager
  = will_paginate programs

.index-entries
  - programs.each do | p |
    = render partial: 'program_capsule', locals: {program: p}
    
.bottom_pager
  = will_paginate programs

app/views/programs/_program_capsule.html.haml
.index-entry
  .page
  .controls
    %span
      = link_to show_icon, program_path(program, page: @page, search: @search), title: 'show'
    %span
      = link_to edit_icon, edit_program_path(program, page: @page, search: @search), title: 'edit'
    %span
      = link_to destroy_icon, program_path(program), method: :delete, title: 'destroy',  class: 'caution', data: {confirm: "Delete #{program.name}?"}
  .index-entry-detail
    = program_capsule program

app/views/programs/_program_person_fields.html.haml
.program-person-fields
  %span.form-group.space-left
    = f.hidden_field :person_id
    - d_id = form_tag_id(f.object_name, :person_id)
    - dl_id = "#{d_id}_link"
    %span{id: dl_id}
      - if f.object.person_id.nil?
        = link_to 'Select person', person_selector_path(dl_id, d_id),  {remote: true, 'data-toggle':  'modal', 'data-target': '#modal-window'}
      - else 
        = f.object.person.name
        %span.caution.space-left
          = link_to_remove_association destroy_icon, f, { wrapper_class: 'programs-person-fields' }

app/views/programs/_programs_person_fields.html.haml
.programs-person-fields
  %span.form-group.space-left
    = f.hidden_field 'director_id'
    - d_id = form_tag_id(f.object_name, 'director_id')
    - dl_id = "#{d_id}_link"
    %span{id: dl_id}
      - if f.object.public_send('director_id').nil?
        = link_to 'Select person', person_selector_path(dl_id, d_id),  {remote: true, 'data-toggle':  'modal', 'data-target': '#modal-window'}
      - else 
        = f.object.person.name
        %span.caution.space-left
          = link_to_remove_association destroy_icon, f, { wrapper_class: 'programs-person-fields' }

app/views/programs/_results.html.haml
= render partial: 'paginated_programs', locals: {programs: @search_results_programs}

app/views/programs/_series_program_fields.html.haml
.series-program-fields
  %span.form-group.space-left
    = f.hidden_field :series_id
    - s_id = form_tag_id(f.object_name, :series_id)
    - sl_id = "#{s_id}_link"
    %span{id: sl_id}
      - if f.object.series_id.nil?
        = link_to 'Select series', series_selector_path(sl_id, s_id),  {remote: true, 'data-toggle':  'modal', 'data-target': '#modal-window'}
      - else 
        = f.object.series.name

app/views/programs/_static_alternate_title_fields.html.haml
.alternate-title
  .nested-fields
    = f.object.name

app/views/programs/duplicates_report.html.haml
%h1 Duplicated Programs

.top-controls
  = link_to 'Program List', programs_url, {class: 'btn btn-primary'}
  = link_to 'Unused Report', reports_program_unused_path, {class: 'btn btn-secondary'}

#paginated-list

  = will_paginate @programs

  .index-entries
    - @programs.each do | p |
      .index-entry
        .index-entry-details
          = duplicate_report_display p

  = will_paginate @programs

app/views/programs/edit.html.haml
%h1 Edit Program

.program
  = form_with model: @program, url: program_path(@program.id, page: @page, search: @search), method: 'patch', id: 'form' do |f|
    .program_fields
      .form-group
        = f.text_field :name, autofocus: true
        = f.label :name
      .form-group
        = f.text_field :sort_name
        = f.label :sort_name
      .form-group
        = f.text_field :year
        = f.label :year
      .form-group
        = f.text_field :version
        = f.label :version
      .form-group
        = f.text_field :minutes
        = f.label :minutes, 'Length'
    = render partial: 'cluster_versions', locals: {mode: 'edit'}
    #program_persons.program_persons
      = f.fields_for :program_persons do |pd_form|
        = render partial: 'program_person_fields', locals: {f: pd_form}
      .links
        = link_to_add_association 'Add Person', f, :program_persons
    #series_programs.series_programs
      = f.fields_for :series_programs do |sp_form|
        = render partial: 'series_program_fields', locals: {f: sp_form}
      .links
        = link_to_add_association 'Add Series', f, :series_programs
    #alternate_titles.alternate_titles
      = f.fields_for :alternate_titles do |at_form|
        = render partial: 'static_alternate_title_fields', locals: {f: at_form}
      .links
        = link_to_add_association 'Add Alternate Title', f, :alternate_titles
    .controls
      = link_to 'Update', '', {onclick: "$('#form').submit()", class: 'btn btn-primary'}
      = link_to "New Version", program_new_version_path(@program.id, page: @page, search: @search), {class: 'btn btn-secondary'}
      = link_to "Cancel", programs_url(page: @page, search: @search), {class: 'btn btn-secondary'}
      
#modal-window.modal.hide{ role: 'dialog', 'aria-labelledby': 'myModalLabel', 'aria-hidden': 'true' }

- if @program.errors.any?
  #error_explanation
    %h2
      = pluralize(@program.errors.count, "error") 
      prohibited this program from being saved:
 
    %ul
      - @program.errors.full_messages.each do |msg|
        %li= msg

app/views/programs/index.html.haml
%h1 Program Index

.top-controls
  = link_to 'New Program', new_program_url, {class: 'btn btn-primary'}
  = link_to 'Duplicates Report', reports_program_duplicates_path, {class: 'btn btn-secondary'}
  = link_to 'Unused Report', reports_program_unused_path, {class: 'btn btn-secondary'}
  = form_tag(programs_path, id: 'search_form', method: :get, remote: true) do
    = text_field_tag :search, params[:search], placeholder: 'Enter search term', autofocus: true

#paginated-list
  = render partial: 'paginated_programs', locals: {programs: @programs}

#search-results

app/views/programs/new.html.haml
%h1 New Program

.program
  = form_with model: @program, id: 'form' do |f|
    .program_fields
      .form-group
        = f.text_field :name, autofocus: true
        = f.label :name
      .form-group
        = f.text_field :sort_name
        = f.label :sort_name
      .form-group
        = f.text_field :year
        = f.label :year
      .form-group
        = f.text_field :version
        = f.label :version
      .form-group
        = f.text_field :minutes
        = f.label :minutes, 'Length'
    #program_persons.program_persons
      = f.fields_for :program_persons do |pd_form|
        = render partial: 'program_person_fields', locals: {f: pd_form}
      .links
        = link_to_add_association 'Add Person', f, :program_persons
    #series_programs.series_programs
      = f.fields_for :series_programs do |sp_form|
        = render partial: 'series_program_fields', locals: {f: sp_form}
      .links
        = link_to_add_association 'Add Series', f, :series_programs
    #alternate_titles.alternate_titles
      = f.fields_for :alternate_titles do |at_form|
        = render partial: 'alternate_title_fields', locals: {f: at_form}
      .links
        = link_to_add_association 'Add Alternate Title', f, :alternate_titles
    .controls
      = link_to 'Create', "", {onclick: "$('#form').submit()", class: 'btn btn-primary'}
      = link_to "Cancel", programs_url, {class: 'btn btn-secondary'}

#modal-window.modal.hide{ role: 'dialog', 'aria-labelledby': 'myModalLabel', 'aria-hidden': 'true' }

- if @program.errors.any?
  #error_explanation
    %h2
      = pluralize(@program.errors.count, "error") 
      prohibited this program from being saved:
 
    %ul
      - @program.errors.full_messages.each do |msg|
        %li= msg

app/views/programs/show.html.haml
%h1 Program

.program
  .titles
    .main_title
      = @program.name
      - unless @program.year.blank?
        = "(#{@program.year})"
    .alternate_titles
      = @program.alternate_titles.map(&:name).join(', ')
  .program_info
    = display_length @program.minutes
    = @program.version
  = render partial: 'cluster_versions', locals: {mode: 'view'}
  - if @program.persons.any?
    .persons
      .label
        = 'Director'.pluralize(@program.persons.count)
      .values
        = raw @program.persons.map{|d| link_to d.name, person_path(d)}.join(', ')
  - if @program.series.any?
    .series
      .label
        Series
      .values
        = raw @program.series.map{|s| link_to s.name, series_path(s) }.join(', ')

.footer-links
  = link_to "Program List", programs_url(page: @page, search: @search), {class: 'btn btn-primary'}
  = link_to "Edit", edit_program_path(@program, page: @page, search: @search), {class: 'btn btn-secondary'}