config/routes.rb
Rails.application.routes.draw do
  root 'programs#index'
  
  resources :programs
  resources :discs
  resources :persons
  resources :locations
  resources :series
  resources :packages
  resources :alternate_titles
  resources :program_version_clusters

  #cloning
  get '/program/:id/new_version', to: 'programs#new_version', as: :program_new_version

  #reports
  get 'reports/program/duplicates', to: 'programs#duplicates_report'
  get 'reports/program/unused', to: 'programs#unused_report'
  get 'reports/disc/no_location', to: 'discs#no_location_report'
  get 'reports/package/no_discs', to: 'packages#no_discs_report'

  #modal selectors
  get "select/program/:link_id/:set_id", to: 'programs#selector', as: :program_selector
  get "select/search/program/:term", to: 'programs#selector_search', as: :program_selector_search
  get "select/person/:link_id/:set_id", to: 'persons#selector', as: :person_selector
  get "select/search/person/:term", to: 'persons#selector_search', as: :person_selector_search
  get "select/series/:link_id/:set_id", to: 'series#selector', as: :series_selector
  get "select/search/series/:term", to: 'series#selector_search', as: :series_selector_search
  get "select/package/:link_id/:set_id", to: 'packages#selector', as: :package_selector
  get "select/search/package/:term", to: 'packages#selector_search', as: :package_selector_search
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/disc.rb
class Disc < ApplicationRecord
  belongs_to :location
  has_many :disc_programs, dependent: :delete_all
  has_many :series_discs, dependent: :delete_all
  has_many :programs, through: :disc_programs
  has_one :disc_package, dependent: :delete
  has_one :package, through: :disc_package
  accepts_nested_attributes_for :disc_programs, reject_if: proc { |attributes| attributes['program_id'].blank? }, allow_destroy: true
  accepts_nested_attributes_for :series_discs, reject_if: proc { |attributes| attributes['series_id'].blank? }
  accepts_nested_attributes_for :disc_package, reject_if: proc { |attributes| attributes['package_id'].blank? }

  before_validation :set_default_location

  FORMATS = %w( DVD Blu-ray Blu-ray\ 3D DVD-R DIGITAL\ COPY CD DVD\ GAME ).freeze 
  validates :format, presence: true, inclusion: { in: FORMATS }

  STATES = %w( UNWATCHED FILED VIEWING LENT ).freeze
  validates :state, presence: true, inclusion: { in: STATES }
  
  def self.not_located
    self.where(location_id: Location.default.id)
  end

  def set_default_location
    self.location ||= Location.default
  end

end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
  
  def index
    if params[:search]
      @search = params[:search]
      @search_results_discs = DiscsSearch.search_by_name(params[:search]).paginate(page: @page, per_page: 15)
      respond_to do |format|
        format.html { @discs = @search_results_discs}
        format.js { render partial: 'search-results'}
      end
    else
      @discs = DiscsSearch.all_by_name.paginate(page: @page, per_page: 15)
    end
  end

  def no_location_report
    @discs = Disc.not_located.paginate(page: params[:page], per_page: 15)
  end

  def show
    @disc = Disc.find params[:id]
    @allow_new = params[:allow_new]
    @search = params[:search]
  end

  def new
    @disc = Disc.new
    @disc.build_disc_package
    @disc.disc_programs.build
    @locations = Location.all_but_default
    @programs = ProgramsSearch.all_by_name
    @packages = Package.all_by_name
  end

  def create
    @disc = Disc.new(disc_params)
    if @disc.save
      redirect_to disc_path(@disc, allow_new: true)
    else
      @locations = Location.all_but_default
      @programs = ProgramsSearch.all_by_name
      @packages = Package.all_by_name
      render 'new'
    end
  end

  def edit
    @disc = Disc.find params[:id]
    @search = params[:search]
    @disc.build_disc_package if @disc.disc_package.nil?
    @locations = Location.all_but_default
    @programs = ProgramsSearch.all_by_name
    @packages = Package.all_by_name
  end

  def update
    @disc = Disc.find params[:id]
    @search = params[:search]
    if @disc.update disc_params 
      redirect_to disc_path(@disc, page: @page, search: @search)
    else
      @locations = Location.all_but_default
      @programs = ProgramsSearch.all_by_name
      @packages = Package.all_by_name
      render 'edit'
    end
  end

  def destroy
    disc = Disc.find params[:id]
    disc.destroy
    redirect_to action: 'index'
  end

  private

  def disc_params
    params.require(:disc).permit(:name, :format, :state, :location_id, 
      disc_package_attributes:[:id, :package_id, :sequence], 
      disc_programs_attributes:[:id, :program_id, :sequence, :program_type, :_destroy],
      series_discs_attributes:[:series_id]
    )
  end

end

app/helpers/discs_helper.rb
module DiscsHelper

  def disc_display_name(disc)
    DiscsSearch.find(disc.id).display_title
  end

  def disc_index_capsule(discs_search)
    package = discs_search.package_name.nil? ? "" : "[#{discs_search.package_name}] "
    "#{package}#{discs_search.display_title} - #{discs_search.format} (#{discs_search.location.name})"
  end

end

app/views/discs/_disc_package_fields.html.haml
.disc-package-fields
  %span.form-group.space-left
    = f.hidden_field :package_id
    - s_id = form_tag_id(f.object_name, :package_id)
    - sl_id = "#{s_id}_link"
    %span{id: sl_id}
      - if f.object.package_id.nil?
        = link_to 'Select package', package_selector_path(sl_id, s_id),  {remote: true, 'data-toggle':  'modal', 'data-target': '#modal-window'}
      - else 
        %span
          = f.object.package.name
        %span.space-left
          = link_to 'Change package', package_selector_path(sl_id, s_id),  {remote: true, 'data-toggle':  'modal', 'data-target': '#modal-window'}

app/views/discs/_disc_program_fields.html.haml
.disc_program_fields
  %span.form-group
    = f.select :program_type, DiscProgram::PROGRAM_TYPES.collect { |pt| [pt, pt] }, {}, multiple: false
    = f.label :program_type
  %span.form-group
    = f.number_field :sequence, in: 1..20, step: 1
    = f.label :sequence
  %span.form-group.space-left
    = f.hidden_field :program_id
    - p_id = form_tag_id(f.object_name, :program_id)
    - pl_id = "#{p_id}_link"
    %span{id: pl_id}
      - if f.object.program_id.nil?
        = link_to 'Select program', program_selector_path(pl_id, p_id),  {remote: true, 'data-toggle':  'modal', 'data-target': '#modal-window'}
      - else 
        = program_select_name(f.object.program)
        %span.caution.space-left
          = link_to_remove_association destroy_icon, f, { wrapper_class: 'disc_program_fields' }

app/views/discs/_paginated_discs.html.haml
.top_pager
  = will_paginate discs

.index-entries
  - discs.each do |disc|
    .index-entry
      .controls
        %span
          = link_to show_icon, disc_path(disc, page: @page, search: @search), title: 'show'
        %span
          = link_to edit_icon, edit_disc_path(disc, page: @page, search: @search), title: 'edit'
        %span
          = link_to destroy_icon, disc_path(disc), method: :delete, title: 'destroy',  class: 'caution', data: {confirm: "Delete #{disc.display_title}?"}
      .index-entry-details
        = disc_index_capsule(disc)
        
.bottom_pager
  = will_paginate discs

app/views/discs/_results.html.haml
= render partial: 'paginated_discs', locals: {discs: @search_results_discs}

app/views/discs/_series_disc_fields.html.haml
.series-disc-fields
  %span.form-group.space-left
    = f.hidden_field :series_id
    - s_id = form_tag_id(f.object_name, :series_id)
    - sl_id = "#{s_id}_link"
    %span{id: sl_id}
      - if f.object.series_id.nil?
        = link_to 'Select series', series_selector_path(sl_id, s_id),  {remote: true, 'data-toggle':  'modal', 'data-target': '#modal-window'}
      - else 
        = f.object.series.name

app/views/discs/edit.html.haml
%h1 Edit Disc

.disc
  = form_with model: @disc, url: disc_path(@disc.id, page: @page, search: @search), method: "patch", id: 'form' do |f|
    .disc_fields
      .form-group
        = f.text_field :name, autofocus: true
        = f.label :name
      .form-group
        = f.select :format, Disc::FORMATS.collect { |fmt| [fmt, fmt] }, {}, multiple: false
        = f.label :format
      .form-group
        = f.select :state, Disc::STATES.collect { |st| [st, st] }, {}, multiple: false
        = f.label :state
      .form-group
        = f.select :location_id, @locations.collect { |loc| [loc.name, loc.id] }, {}, multiple: false
        = f.label :location_id
        
    #disc_packages.disc_packages
      = f.fields_for :disc_package do |dpkg_form|
        = render partial: 'disc_package_fields', locals: {f: dpkg_form}

    #disc_programs.disc_programs
      = f.fields_for :disc_programs do |dp_form|
        = render partial: 'disc_program_fields', locals: {f: dp_form}
      .links
        = link_to_add_association 'Add Program', f, :disc_programs

    #series_discs.series_discs
      = f.fields_for :series_discs do |ds_form|
        = render partial: 'series_disc_fields', locals: {f: ds_form}
      .links
        = link_to_add_association 'Add Series', f, :series_discs

    .controls
      = link_to 'Update', "", {onclick: "$('#form').submit()", class: 'btn btn-primary'}
      = link_to "Cancel", discs_url(page: @page, search: @search), {class: 'btn btn-secondary'}

#modal-window.modal.hide{ role: 'dialog', 'aria-labelledby': 'myModalLabel', 'aria-hidden': 'true' }

- if @disc.errors.any?
  #error_explanation
    %h2
      = pluralize(@disc.errors.count, "error") 
      prohibited this disc from being saved:
 
    %ul
      - @disc.errors.full_messages.each do |msg|
        %li= msg

app/views/discs/index.html.haml
%h1 Disc Index

.top-controls
  = link_to 'New Disc', new_disc_url, {class: 'btn btn-primary'}
  = link_to 'No Location Report', reports_disc_no_location_path, {class: 'btn btn-secondary'}
  = form_tag(discs_path, id: 'search_form', method: :get, remote: true) do
    = text_field_tag :search, params[:search], placeholder: 'Enter search term', autofocus: true

#paginated-list
  = render partial: 'paginated_discs', locals: {discs: @discs}

#search-results

app/views/discs/new.html.haml
%h1 New Disc

.disc
  = form_with model: @disc, id: 'form' do |f|
    .disc_fields
      .form-group
        = f.text_field :name, autofocus: true
        = f.label :name
      .form-group
        = f.select :format, Disc::FORMATS.collect { |fmt| [fmt, fmt] }, {}, multiple: false
        = f.label :format
      .form-group
        = f.select :state, Disc::STATES.collect { |st| [st, st] }, {}, multiple: false
        = f.label :state
      .form-group
        = f.select :location_id, @locations.collect { |loc| [loc.name, loc.id] }, {include_blank: ''}, multiple: false
        = f.label :location_id

    #disc_packages.disc_packages
      = f.fields_for :disc_package do |dpkg_form|
        = render partial: 'disc_package_fields', locals: {f: dpkg_form}

    #disc_programs.disc_programs
      = f.fields_for :disc_programs do |dp_form|
        = render partial: 'disc_program_fields', locals: {f: dp_form}
      .links
        = link_to_add_association 'Add Program', f, :disc_programs

    #series_discs.series_discs
      = f.fields_for :series_discs do |ds_form|
        = render partial: 'series_disc_fields', locals: {f: ds_form}
      .links
        = link_to_add_association 'Add Series', f, :series_discs

    .controls
      = link_to 'Create', "", {onclick: "$('#form').submit()", class: 'btn btn-primary'}
      = link_to "Cancel", discs_url, {class: 'btn btn-secondary'}

#modal-window.modal.hide{ role: 'dialog', 'aria-labelledby': 'myModalLabel', 'aria-hidden': 'true' }

- if @disc.errors.any?
  #error_explanation
    %h2
      = pluralize(@disc.errors.count, "error") 
      prohibited this disc from being saved:
 
    %ul
      - @disc.errors.full_messages.each do |msg|
        %li= msg

app/views/discs/no_location_report.html.haml
%h1 No Location Discs

.top-controls
  = link_to 'Disc List', discs_url, {class: 'btn btn-primary'}

#paginated-list
  = will_paginate @discs

  .index-entries
    - @discs.each do |disc|
      .index-entry
        .index-entry-details
          - disc_text = "#{disc_display_name disc} (#{disc.format})"
          = link_to disc_text, disc_path(disc)
          
  = will_paginate @discs

app/views/discs/show.html.haml
%h1 Disc

.disc
  .name
    = disc_display_name @disc
  .format
    = @disc.format
  .state
    = @disc.state
    = "(#{@disc.location.name})"
  - unless @disc.package.nil?
    .package
      - package_text = "Part of #{@disc.package.name}"
      = link_to package_text, package_path(@disc.package)

  .disc_programs
    = 'No Programs Listed' if @disc.disc_programs.empty?
    - @disc.disc_programs.each do |dp|
      .program
        %span.name
          = link_to program_capsule_year(dp.program), program_path(dp.program)
        - unless dp.program.version.blank?
          %span.version
            = "(#{dp.program.version})"
        %span.type
          = dp.program_type

  - if @disc.series_discs.any?
    .series_discs
      - @disc.series_discs.each do |sd|
        .series
          %span.name
            = link_to sd.series.name, series_path(sd.series)
.footer-links
  = link_to "Disc List", discs_url(page: @page, search: @search), {class: 'btn btn-primary'}
  - if @allow_new
    = link_to 'New Disc', new_disc_url, {class: 'btn btn-secondary'}
  = link_to "Edit", edit_disc_path(@disc, page: @page, search: @search), {class: 'btn btn-secondary'}