config/routes.rb
Rails.application.routes.draw do
  root 'programs#index'
  
  resources :programs
  resources :discs
  resources :persons
  resources :locations
  resources :series
  resources :packages
  resources :alternate_titles
  resources :program_version_clusters

  #cloning
  get '/program/:id/new_version', to: 'programs#new_version', as: :program_new_version

  #reports
  get 'reports/program/duplicates', to: 'programs#duplicates_report'
  get 'reports/program/unused', to: 'programs#unused_report'
  get 'reports/disc/no_location', to: 'discs#no_location_report'
  get 'reports/package/no_discs', to: 'packages#no_discs_report'

  #modal selectors
  get "select/program/:link_id/:set_id", to: 'programs#selector', as: :program_selector
  get "select/search/program/:term", to: 'programs#selector_search', as: :program_selector_search
  get "select/person/:link_id/:set_id", to: 'persons#selector', as: :person_selector
  get "select/search/person/:term", to: 'persons#selector_search', as: :person_selector_search
  get "select/series/:link_id/:set_id", to: 'series#selector', as: :series_selector
  get "select/search/series/:term", to: 'series#selector_search', as: :series_selector_search
  get "select/package/:link_id/:set_id", to: 'packages#selector', as: :package_selector
  get "select/search/package/:term", to: 'packages#selector_search', as: :package_selector_search
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController

  def index
    if params[:search]
      @search = params[:search]
      @search_results_series = Series.search_name(params[:search]).paginate(page: @page, per_page: 15)
      respond_to do |format|
        format.html { @series = @search_results_series}
        format.js { render partial: 'search-results'}
      end
    else
      @series = Series.all_sort_by_name.paginate(page: @page, per_page: 15)
    end
  end

  def show
    @series = Series.find params[:id]
    @search = params[:search]
  end

  def new
    @series = Series.new
  end

  def create
    @series = Series.new series_params
    if @series.save
      redirect_to @series
    else
      render "new"
    end
  end

  def edit
    @series = Series.find params[:id]
    @search = params[:search]
  end

  def update
    @series = Series.find params[:id]
    @search = params[:search]
    if @series.update series_params
      redirect_to series_path(@series, page: @page, search: @search) 
    else
      render "edit"
    end
  end

  def destroy
    series = Series.find params[:id]
    series.destroy
    redirect_to action: 'index'
  end

  def selector
    @set_id = params[:set_id]
    @link_id = params[:link_id]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def selector_search
    search_term = params[:term]
    @series = Series.search_name search_term
    respond_to do |format|
      format.js
    end
  end

  private

  def series_params
    params.require(:series).permit(
      :name, 
      series_programs_attributes:[:id, :sequence, :series_id, :program_id, :_destroy], 
      contained_series_series_attributes:[:id, :sequence, :wrapper_series_id, :contained_series_id, :_destroy], 
      wrapper_series_series_attributes:[:id, :sequence, :wrapper_series_id, :contained_series_id],
      series_discs_attributes:[:id, :sequence, :series_id, :disc_id, :_destroy],
      series_packages_attributes:[:id, :sequence, :series_id, :package_id, :_destroy]
    )
  end

end

app/helpers/series_helper.rb
module SeriesHelper

  def series_capsule_array(series)
    return_array = []
    series.series_programs.each do |sp|
      return_array << sequenced_series_capsule(sp)
    end
    series.contained_series_series.each do |cs|
      return_array << sequenced_series_capsule(cs)
    end
    series.series_discs.each do |sd|
      return_array << sequenced_series_capsule(sd)
    end
    series.series_packages.each do |spa|
      return_array << sequenced_series_capsule(spa)
    end
    return_array.sort_by { |ssc| ssc[:seq] }
  end

  def sequenced_series_capsule(series_assoc)
    {
      seq: series_assoc.safe_sequence,
      display_capsule: series_capsule(series_assoc),
      id: series_capsule_id(series_assoc),
      path_method: series_capsule_path(series_assoc)
    }
  end

  def capsule_series_program(series_program)
    year = series_program.program.year.blank? ? '' : " (#{series_program.program.year})"
    version = series_program.program.version.blank? ? '' : " - #{series_program.program.version}"
    "#{series_program.program.name}#{year}#{version}"
  end

  def capsule_series_series(series_series)
    programs = series_series.contained_series.series_programs
    program_count = programs.any? ? " [#{programs.count}]" : ''
    "#{series_series.contained_series.name}#{program_count}"
  end

  def capsule_series_disc(series_disc)
    disc_id = series_disc.disc_id
    DiscsSearch.find(disc_id).display_title
  end

  def capsule_series_package(series_package)
    series_package.package.name
  end

  private 

  def series_capsule(series_assoc)
    if series_assoc.respond_to? :program
      capsule_series_program series_assoc
    elsif series_assoc.respond_to? :disc
      capsule_series_disc series_assoc
    elsif series_assoc.respond_to? :package
      capsule_series_package series_assoc
    else
      capsule_series_series series_assoc
    end
  end

  def series_capsule_id(series_assoc)
    if series_assoc.respond_to? :program
      series_assoc.program.id
    elsif series_assoc.respond_to? :disc
      series_assoc.disc.id
    elsif series_assoc.respond_to? :package
      series_assoc.package.id
    else
      series_assoc.contained_series.id
    end
  end

  def series_capsule_path(series_assoc)
    if series_assoc.respond_to? :program
      'program_path'
    elsif series_assoc.respond_to? :disc
      'disc_path'
    elsif series_assoc.respond_to? :package
      'package_path'
    else
      'series_path'
    end
  end


end

app/views/series/_paginated_series.html.haml
.top_pager
  = will_paginate series

.index-entries
  - series.each do |ser|
    .index-entry
      .controls
        %span
          = link_to show_icon, series_path(ser, page: @page, search: @search), title: 'show'
        %span
          = link_to edit_icon, edit_series_path(ser, page: @page, search: @search), title: 'edit'
        %span
          = link_to destroy_icon, series_path(ser), method: :delete,  class: 'caution', title: 'destroy', data: {confirm: "Delete #{ser.name}?"}
      .index-entry-details
        = ser.name

.bottom_pager
  = will_paginate series

app/views/series/_results.html.haml
= render partial: 'paginated_series', locals: {series: @search_results_series}

app/views/series/_series_series_fields.html.haml
.series-series-fields
  %span.form-group.space-left
    = f.hidden_field :contained_series_id
    = f.hidden_field :wrapper_series_id
    - s_id = form_tag_id(f.object_name, :wrapper_series_id)
    - sl_id = "#{s_id}_link"
    %span{id: sl_id}
      - if f.object.wrapper_series_id.nil?
        = link_to 'Select series', series_selector_path(sl_id, s_id),  {remote: true, 'data-toggle':  'modal', 'data-target': '#modal-window'}
      - else 
        = f.object.wrapper_series.name

app/views/series/_wrapper_series_series_fields.html.haml
.series-series-fields
  %span.form-group.space-left
    = f.hidden_field :contained_series_id
    = f.hidden_field :wrapper_series_id
    - s_id = form_tag_id(f.object_name, :wrapper_series_id)
    - sl_id = "#{s_id}_link"
    %span{id: sl_id}
      - if f.object.wrapper_series_id.nil?
        = link_to 'Select series', series_selector_path(sl_id, s_id),  {remote: true, 'data-toggle':  'modal', 'data-target': '#modal-window'}
      - else 
        = f.object.wrapper_series.name

app/views/series/edit.html.haml
%h1 Edit Series

.series
  = form_with model: @series, url: series_path(@series.id, page: @page, search: @search), method: "patch", id: 'form' do |f|
    .series_fields
      .form-group
        = f.text_field :name, autofocus: true
        = f.label :name
    .series_capsules
      = f.fields_for :series_programs, @series.series_programs.sort_by {|sp| sp.safe_sequence} do |sp_form|
        .series_capsule{style: "order: #{sp_form.object.sequence}"}
          = sp_form.hidden_field :program_id
          .form-group
            = sp_form.label :sequence
            = sp_form.number_field :sequence, in: 1..500, step: 1
            %span.capsule_name
              = sp_form.object.program.name
            %span.caution.space-left
              = link_to_remove_association destroy_icon, sp_form, { wrapper_class: 'series_capsule' }
      = f.fields_for :series_discs, @series.series_discs.sort_by {|sd| sd.safe_sequence} do |sd_form|
        .series_capsule{style: "order: #{sd_form.object.sequence}"}
          = sd_form.hidden_field :disc_id
          .form-group
            = sd_form.label :sequence
            = sd_form.number_field :sequence, in: 1..500, step: 1
            %span.capsule_name
              - ds = DiscsSearch.find(sd_form.object.disc.id)
              = ds.display_title
            %span.caution.space-left
              = link_to_remove_association destroy_icon, sd_form, { wrapper_class: 'series_capsule' }
      = f.fields_for :series_packages, @series.series_packages.sort_by {|sp| sp.safe_sequence} do |sp_form|
        .series_capsule{style: "order: #{sp_form.object.sequence}"}
          = sp_form.hidden_field :package_id
          .form-group
            = sp_form.label :sequence
            = sp_form.number_field :sequence, in: 1..500, step: 1
            %span.capsule_name
              - pack = sp_form.object.package
              = pack.name
            %span.caution.space-left
              = link_to_remove_association destroy_icon, sp_form, { wrapper_class: 'series_capsule' }
      = f.fields_for :contained_series_series, @series.contained_series_series.sort_by {|css| css.safe_sequence} do |css_form|
        .series_capsule{style: "order: #{css_form.object.sequence}"}
          = css_form.hidden_field :contained_series_id
          .form-group
            = css_form.label :sequence
            = css_form.number_field :sequence, in: 1..500, step: 1
            %span.capsule_name
              = css_form.object.contained_series.name
            %span.caution.space-left
              = link_to_remove_association destroy_icon, css_form, { wrapper_class: 'series_capsule' }
    #wrapper_series_series.wrapper_series_series
      = f.fields_for :wrapper_series_series do |wss_form|
        = render partial: 'wrapper_series_series_fields', locals: {f: wss_form}
      .links
        = link_to_add_association 'Add Wrapper Series', f, :wrapper_series_series
    .controls
      = link_to 'Update', "", {onclick: "$('#form').submit()", class: 'btn btn-primary'}
      = link_to "Cancel", series_index_url(page: @page, search: @search), {class: 'btn btn-secondary'}
      
#modal-window.modal.hide{ role: 'dialog', 'aria-labelledby': 'myModalLabel', 'aria-hidden': 'true' }

- if @series.errors.any?
  #error_explanation
    %h2
      = pluralize(@series.errors.count, "error") 
      prohibited this series from being saved:
 
    %ul
      - @series.errors.full_messages.each do |msg|
        %li= msg

app/views/series/index.html.haml
%h1 Series Index

.top-controls
  = link_to 'New Series', new_series_url, {class: 'btn btn-primary'}
  = form_tag(series_index_path, id: 'search_form', method: :get, remote: true) do
    = text_field_tag :search, params[:search], placeholder: 'Enter search term', autofocus: true

#paginated-list
  = render partial: 'paginated_series', locals: {series: @series}

#search-results

app/views/series/new.html.haml
%h1 New Series

.series
  = form_with model: @series, id: 'form' do |f|
    .series_fields
      .form-group
        = f.text_field :name, autofocus: true
        = f.label :name
    .controls
      = link_to 'Create', "", {onclick: "$('#form').submit()", class: 'btn btn-primary'}
      = link_to "Cancel", series_index_url, {class: 'btn btn-secondary'}

- if @series.errors.any?
  #error_explanation
    %h2
      = pluralize(@series.errors.count, "error") 
      prohibited this series from being saved:
 
    %ul
      - @series.errors.full_messages.each do |msg|
        %li= msg

app/views/series/selector.js.erb
$("#modal-window").html("<%= escape_javascript(render partial: 'common/selector', locals: {set_id: @set_id, link_id: @link_idj, name: 'Series', search_path: lambda {|arg| series_selector_search_path(arg)}}) %>");
$('#select_search').trigger('focus');

app/views/series/selector_search.js.erb
$('#selected_id_value').html("<%= escape_javascript(render partial: 'common/filtered_selector', locals: {objects: @series, option_lambda: lambda { |ser| ser.name }}) %>");

app/views/series/show.html.haml
%h1 Series

.series
  .name
    = @series.name
  - series_capsule_array = series_capsule_array @series
  - if series_capsule_array.any?
    .series_capsules
      .label
        Contains
      - series_capsule_array.sort_by{|sc| sc[:seq]}.each do |sc|
        .series_capsule
          %span.sequence
            = sc[:seq]
          %span.capsule
            = link_to sc[:display_capsule], public_send(sc[:path_method], sc[:id])
  - if @series.wrapper_series_series.any?
    .wrapper_series_series
      .label
        Part of Series
      - @series.wrapper_series_series.each do |wss|
        .wrapper_series
          = link_to wss.wrapper_series.name, series_path(wss.wrapper_series)

.footer-links
  = link_to "Series List", series_index_url(page: @page, search: @search), {class: 'btn btn-primary'}
  = link_to "Edit", edit_series_path(@series, page: @page, search: @search), {class: 'btn btn-secondary'}